### ISSUE TITLE
Feedback for Home Page

### ISSUE THREAD

**Issue by chaudhary6-1** [brishnafarahi/safe_signs_limited#3]
![homepage](https://user-images.githubusercontent.com/75631983/103444519-2e7aaa00-4c69-11eb-8b8e-57ba53b67222.png)

**Comment by KingsleyOdiboh** [comment]
Thanks for the great work guys and for the efforts so far. If its not too much work, could you maybe make the prominent colour white instead of black and sky-blue for the other boxes? We feel changing the colors would make the site more lively. Maybe the video viewbox can be more bigger. Do you feel this layout of the home page is better than our original thoughts for the home page layout?

Thanks once more guys!

**Comment by chaudhary6-1** [comment]
![home](https://user-images.githubusercontent.com/75631983/103473182-f3c26000-4d95-11eb-9c66-f3d41c4ba426.png)

I personally finds brighter color scheme really irritating for the eye and we tried with white and blue as proposed in description but they wont really match together as well. That is why we want to go with something more comfortable for the eye.

**Comment by chaudhary6-1** [comment]
![homepage](https://user-images.githubusercontent.com/75631983/103473460-39345c80-4d99-11eb-8f2f-a34a204dc366.png)

Video size increased with oringinal color schemes

**Comment by chaudhary6-1** [comment]
![homepage_reworked](https://user-images.githubusercontent.com/75631983/103932079-9aee2100-5121-11eb-9374-c011e3c7f778.png)


> Maybe the video viewbox can be more bigger. Do you feel this layout of the home page is better than our original thoughts for the home page layout?
> 
> Thanks once more guys!

Video and sample products reworked as wished in layout.

**Comment by KingsleyOdiboh** [comment]
The layout is fine...
